--- #YAML:1.0
name:               Date-RangeParser-EN
version:            0.03
abstract:           Parser for plain English date/time range strings
author:
    - Michael Aquilina <aquilina@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Date::Manip:  0
    DateTime:     0
no_index:
    directory:
        - t
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
